version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Directory tree"
      - ls -R .
      - echo "Now running mvn"
      - mvn -B package --file pom.xml


artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*.sh
    - scripts/stop_app.sh       # hook #1
    - scripts/start_app.sh      # hook #2
    - scripts/verify_health.sh
    - AWSTemplateFormateVersion2.yaml
    - DevOpsWebAppStack-deployment.yaml
