version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Directory tree"
      - ls -R .
      - echo "Now running mvn"
      - mvn -B package --file pom.xml

artifacts:
  files:
    - artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*.sh
    - scripts/AWSTemplateFormatVersion2.yaml
    - scripts/DevOpsWebAppStack-deployment.yaml
    - target/DevOpsSummative-1.0-SNAPSHOT.jar
